Refactor GeolocatorService.Reactive
nventive/GeolocatorService pull request #24
Opened 2023-12-07 18:33 UTC by charlesericlanglois

GitHub Issue: #

## Proposed Changes

## What is the current behavior?

GeolocatorService.Reactive is divided between GeolocatorService.Reactive.Uno.UI and GeolocatorService.Reactive.Shared

## What is the new behavior?

There is only one GeolocatorService.Reactive package

## Checklist

Please check if your PR fulfills the following requirements:

- [ ] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [ ] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [x] Associated with an issue

Use the GeolocatorService.Reactive package instead of GeolocatorService.Reactive.Uno.UI or GeolocatorService.Reactive.Shared

## Other information

2023-12-07 19:29 UTC, jeanplevesque requested changes

2023-12-07 19:29 UTC, jeanplevesque commented on GeolocatorService.sln
>  EndProject
The newly added files are good, but you also need to remove the ones that shouldn't be there. They need to be removed from the repository.

2023-12-07 19:29 UTC, jeanplevesque commented on GeolocatorService.sln
>  EndProject
You checked the "No breaking changes" box, but changing the structure of the packages **is a breaking change** and it needs to be documented.

2023-12-07 19:57 UTC, charlesericlanglois commented on GeolocatorService.sln
>  EndProject
Done

2023-12-07 19:58 UTC, charlesericlanglois commented on GeolocatorService.sln
>  EndProject
I misunderstood that checkbox, let me know if my description works

2023-12-07 20:30 UTC, jeanplevesque requested changes

2023-12-07 20:30 UTC, jeanplevesque commented on GeolocatorService.sln
>  EndProject
You also need to document the breaking change in BREAKING_CHANGES.md, you can take a look at this as an example: https://github.com/nventive/Chinook.DynamicMvvm/blob/main/BREAKING_CHANGES.md

2023-12-07 20:52 UTC, charlesericlanglois commented on GeolocatorService.sln
>  EndProject
Done

2023-12-18 14:30 UTC, jeanplevesque commented on src/GeolocatorService.Reactive/GeolocatorServiceExtensions.cs
> +			var currentLocationOrNull = isPermissionGranted ? await service.GetLocation(ct) : null;
Should this be changed?

2023-12-18 16:10 UTC, charlesericlanglois commented on src/GeolocatorService.Reactive/GeolocatorServiceExtensions.cs
> +			var currentLocationOrNull = isPermissionGranted ? await service.GetLocation(ct) : null;
No, I just reverted it

2023-12-20 14:05 UTC, jeanplevesque approved these changes

2023-12-20 14:11 UTC, merged